name: Build TWRP from Custom Tree

on:
  workflow_dispatch:
    inputs:
      DEVICE_TREE_URL:
        description: 'Device Tree Repo URL'
        required: true
        default: 'https://github.com/AHL8192/device_gplus_Q10'
      DEVICE_PATH:
        description: 'Device Tree Path (e.g., device/gplus/Q10)'
        required: true
        default: 'device/gplus/Q10'
      MAKEFILE_NAME:
        description: 'Makefile Name'
        required: true
        default: 'omni_Q10'
      DEVICE_NAME:
        description: 'Device Name'
        required: true
        default: 'Q10'
      MANIFEST_URL:
        description: 'MANIFEST_URL'
        required: true
        default: 'https://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni'
      MANIFEST_BRANCH:
        description: 'MANIFEST_BRANCH'
        required: true
        default: 'twrp-9.0'
      BUILD_TARGET:
        description: 'BUILD_TARGET'
        required: true
        default: 'recovery'

jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
    - name: Display Run Parameters
      run: |
        echo "::group::User Environment Variables"
        echo "Manifest URL: ${{ inputs.MANIFEST_URL }}"
        echo "Manifest Branch: ${{ inputs.MANIFEST_BRANCH }}"
        echo "Device Tree: ${{ inputs.DEVICE_TREE_URL }}"
        echo "Build Target: ${{ inputs.BUILD_TARGET }}.img"
        echo "::endgroup::"

    - name: Check Out
      uses: actions/checkout@v4
      
    - name: Cleanup
      uses: rokibhasansagar/slimhub_actions@main

    - name: Prepare the environment
      run: |
        sudo apt-get update
        sudo apt-get -y upgrade
        sudo apt-get -y install gperf gcc-multilib gcc-10-multilib g++-multilib g++-10-multilib libc6-dev lib32ncurses5-dev x11proto-core-dev libx11-dev tree lib32z-dev libgl1-mesa-dev libxml2-utils xsltproc bc ccache lib32readline-dev lib32z1-dev liblz4-tool libncurses5-dev libsdl1.2-dev libwxgtk3.0-gtk3-dev libxml2 lzop pngcrush schedtool squashfs-tools imagemagick libbz2-dev lzma ncftp qemu-user-static libstdc++-10-dev libncurses5 python3 python3-pip cpio wget

    - name: Install OpenJDK
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '8'

    - name: Setup SSH Keys
      if: ${{ startsWith(inputs.MANIFEST_URL, 'git@github.com') }}
      uses: webfactory/ssh-agent@v0.9.0
      with:
          ssh-private-key: |
              ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Install repo
      run: |
        mkdir ~/bin
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
        chmod a+x ~/bin/repo
        sudo ln -sf ~/bin/repo /usr/bin/repo

    - name: Initialize repo
      run: |
        mkdir workspace
        cd workspace
        echo "workspace-folder=$(pwd)" >> $GITHUB_OUTPUT
        git config --global user.name "AHL8192"
        git config --global user.email "actions@github.com"
        repo init --depth=1 -u ${{ inputs.MANIFEST_URL }} -b ${{ inputs.MANIFEST_BRANCH }}
      id: pwd

    - name: Repo Sync
      run: |
        repo sync -j$(nproc --all) --force-sync
      working-directory: workspace
      
    - name: Clone Custom Device Tree
      run: |
        git clone ${{ inputs.DEVICE_TREE_URL }} ${{ inputs.DEVICE_PATH }}
      working-directory: ${{ steps.pwd.outputs.workspace-folder }}

    - name: Sync Device Dependencies
      run: |
        DEP_FILE=$(find ${{ inputs.DEVICE_PATH }} -name "*.dependencies" | head -n 1)
        if [ -n "$DEP_FILE" ]; then
          bash ${GITHUB_WORKSPACE}/scripts/convert.sh "$DEP_FILE"
          repo sync -j$(nproc --all)
        else
          echo "No dependencies file found, skipping..."
        fi
      working-directory: ${{ steps.pwd.outputs.workspace-folder }}
      continue-on-error: true

    - name: Set Swap Space
      uses: pierotofy/set-swap-space@master
      with:
        swap-size-gb: 12

    - name: Switch to Python2
      run: |
        sudo apt-get -y install python2
        sudo rm -f /usr/bin/python
        sudo ln -s /usr/bin/python2 /usr/bin/python
      continue-on-error: true

    - name: Building recovery
      run: |
        source build/envsetup.sh
        export ALLOW_MISSING_DEPENDENCIES=true
        lunch ${{ inputs.MAKEFILE_NAME }}-eng
        make clean
        make ${{ inputs.BUILD_TARGET }}image -j$(nproc --all)
      working-directory: ${{ steps.pwd.outputs.workspace-folder }}

    - name: Upload to Release
      uses: softprops/action-gh-release@v2
      with:
        files: | 
          workspace/out/target/product/*/${{ inputs.BUILD_TARGET }}.img
          workspace/out/target/product/*/*.zip
          workspace/out/target/product/*/*vendor*.img
        name: ${{ inputs.DEVICE_NAME }}-${{ github.run_id }}
        tag_name: ${{ github.run_id }}
        body: |
          Manifest: ${{ inputs.MANIFEST_BRANCH }}
          Device: ${{ inputs.DEVICE_NAME }}
          Target: ${{ inputs.BUILD_TARGET }}.img
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
